* andrew Global
background started out working in service provider and then went to 
univisity of utah. He would have to do security on call for a while 
there. He worked full time on the secirty team for a few years. 

cissp is the cert he has. He also has to make and push policies.

To break into security find someting you are good at and become 
very good at it and learn all the security for it. 

2.2 million records were lost after the backup taps had been stolen out of
a car. The law enforcement said to offer a 500 dollar reward for the return
of the taps. Methheads had taken them and tried to play the taps in their vcr
their friend turned them in for the reward money. They had lost over 5 million
dollars from it.

They could have prevented it by encrypting the backup taps. 

Hackers are filing tax returns in someone elses name so they get the money
back. 

They are trying to seperate into levels development, testing, production.

** security
sans 
twitter 
pen testing

** tools        
Vanina snort 
identity finder
netflow
nfdump

